out_dir: results
metric_best: mrr
num_workers: 4
tensorboard_agg: False
tensorboard_each_run: False
wandb:
  use: False
  project: pcqm4m-contact
dataset:
  dir: ./data
  format: OGB
  name: PCQM4Mv2Contact-shuffle
  task: graph # PCQM4Mv2Contact is edge-level task, but because it is inductive, set to 'graph'
  task_type: classification
  resample_negative: True
  transductive: False
  node_encoder: True
  node_encoder_name: Atom+LapPE
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: Bond
  edge_encoder_bn: False
posenc_LapPE:
  enable: True
  eigen:
    laplacian_norm: none
    eigvec_norm: L2
    max_freqs: 10
  model: DeepSet
  dim_pe: 16
  layers: 2
  raw_norm_type: none
train:
  mode: custom
  batch_size: 256
  eval_period: 1
  ckpt_period: 100
model:
  type: custom_gnn
  loss_fun: cross_entropy
  edge_decoding: dot
gvm:
  avg_nodes: 35
  pool_ratio: 0.9
  n_pool_heads: 1
  na_order: fixed
gnn:
  head: inductive_edge
  layers_pre_mp: 0
  layers_mp: 7
  layers_post_mp: 1
  dim_inner: 100
  layer_type: gcniiconv
  stage_type: stack
  batchnorm: True
  act: relu
  dropout: 0.0
  agg: mean
  normalize_adj: False
optim:
  optimizer: adamW
  weight_decay: 0.0
  base_lr: 0.0003
  max_epoch: 200
  scheduler: cosine_with_warmup
  num_warmup_epochs: 10
  min_lr: 1e-5
