out_dir: results
metric_best: accuracy
tensorboard_agg: False
tensorboard_each_run: False
wandb:
  use: False
dataset:
  format: OGB
  name: ogbn-arxiv
  task: node
  task_type: classification
  transductive: False
  node_encoder: True
  node_encoder_name: LinearNode
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: DummyEdge
  edge_encoder_bn: False
train:
  mode: custom
  batch_size: 1
  eval_period: 1
  ckpt_period: 100
model:
  type: custom_gnn
  loss_fun: cross_entropy
  edge_decoding: dot
  graph_pooling: add
gvm:
  avg_nodes: 169343
  pool_ratio: 0.000001
  n_pool_heads: 1
# 2 / 100 for Neural Atom
gnn:
  head: inductive_node
  layers_pre_mp: 0
  layers_mp: 1
  layers_post_mp: 0
  dim_inner: 16
  layer_type: gcn
  stage_type: stack
  batchnorm: True
  act: relu
  dropout: 0.12
  agg: add
  normalize_adj: False
optim:
  optimizer: adamW
  weight_decay: 0.0
  base_lr: 0.0003
  max_epoch: 5
  scheduler: cosine_with_warmup
  num_warmup_epochs: 10
  min_lr: 1e-5
