out_dir: results
metric_best: mrr
tensorboard_agg: False
tensorboard_each_run: False
num_workers: 4
wandb:
  use: False
  project: pcqm4m-contact
dataset:
  dir: ./data
  format: OGB
  name: PCQM4Mv2Contact-shuffle
  task: graph # PCQM4Mv2Contact is edge-level task, but because it is inductive, set to 'graph'
  task_type: classification
  resample_negative: True
  transductive: False
  node_encoder: True
  node_encoder_name: Atom+RWSE+LapPE
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: Bond
  edge_encoder_bn: False
posenc_RWSE:
  enable: True
  kernel:
    times_func: range(1,17)
  model: Linear
  dim_pe: 20
  raw_norm_type: BatchNorm
posenc_LapPE:
  enable: True
  eigen:
    laplacian_norm: none
    eigvec_norm: L2
    max_freqs: 10
  model: DeepSet
  dim_pe: 16
  layers: 2
  raw_norm_type: none
train:
  mode: custom
  batch_size: 256
  eval_period: 1
  ckpt_period: 100
gvm:
  avg_nodes: 35
  pool_ratio: 0.6
  n_pool_heads: 1
  na_order: fixed
model:
  type: custom_gnn
  loss_fun: cross_entropy
  edge_decoding: dot
gnn:
  head: inductive_edge
  layers_pre_mp: 0
  layers_mp: 6
  layers_post_mp: 1
  dim_inner: 80
  layer_type: gatedgcnconv
  act: relu
  residual: True
  dropout: 0.12
optim:
  optimizer: adamW
  weight_decay: 0.0
  base_lr: 0.001
  max_epoch: 200
  scheduler: reduce_on_plateau
  reduce_factor: 0.5
  schedule_patience: 10
  min_lr: 1e-5
