out_dir: results
metric_best: mrr
tensorboard_agg: False
tensorboard_each_run: False
wandb:
  use: False
  project: pcqm4m-contact
dataset:
  dir: /datastorage/xuanli/lrgb/LRGB
  format: OGB
  name: PCQM4Mv2Contact-shuffle
  task: graph # PCQM4Mv2Contact is edge-level task, but because it is inductive, set to 'graph'
  task_type: classification
  resample_negative: True
  transductive: False
  node_encoder: True
  node_encoder_name: Atom
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: Bond
  edge_encoder_bn: False
train:
  mode: custom
  batch_size: 256
  eval_period: 1
  ckpt_period: 100
model:
  type: vm_gnn
  loss_fun: cross_entropy
  edge_decoding: dot
gnn:
  head: inductive_edge
  layers_pre_mp: 0
  layers_mp: 5
  layers_post_mp: 1
  dim_inner: 208
  layer_type: gineconv
  act: relu
  residual: True
  dropout: 0.0
vm:
  vn_residual: True
  vn_drop_ratio: 0.0
optim:
  optimizer: adamW
  weight_decay: 0.0
  base_lr: 0.001
  max_epoch: 200
  scheduler: cosine_with_warmup
  num_warmup_epochs: 20
  min_lr: 1e-5
