out_dir: results
metric_best: mae
metric_agg: argmin
tensorboard_agg: False
tensorboard_each_run: False
wandb:
  use: False
  project: peptides-struct
dataset:
  dir: /data/csxuanli/LRGB/
  format: OGB
  name: peptides-structural
  task: graph
  task_type: regression
  transductive: False
  node_encoder: True
  node_encoder_name: Atom+LapPE
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: Bond
  edge_encoder_bn: False
posenc_LapPE:
  enable: True
  eigen:
    laplacian_norm: none
    eigvec_norm: L2
    max_freqs: 10
  model: DeepSet
  dim_pe: 16
  layers: 2
  raw_norm_type: none
train:
  mode: custom
  batch_size: 128
  eval_period: 1
  ckpt_period: 100
model:
  type: custom_gnn
  loss_fun: l1
  graph_pooling: mean
gvm:
  avg_nodes: 150
  pool_ratio: 0.12
  n_pool_heads: 2
gnn:
  layers_pre_mp: 0
  layers_mp: 4
  layers_post_mp: 1
  dim_inner: 88
  layer_type: gineconv
  act: relu
  residual: True
  dropout: 0.0
optim:
  optimizer: adamW
  weight_decay: 0.0
  base_lr: 0.0003
  max_epoch: 200
  scheduler: cosine_with_warmup
  num_warmup_epochs: 10
  min_lr: 1e-5
