out_dir: results
metric_best: accuracy
tensorboard_agg: False
tensorboard_each_run: False
wandb:
  use: False
dataset:
  format: PyG-Amazon
  name: computers
  task: node
  task_type: classification
  transductive: True
  node_encoder: True
  node_encoder_name: LinearNode
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: DummyEdge
  edge_encoder_bn: False
  split: [0.6, 0.2, 0.2]
posenc_LapPE:
  enable: True
  eigen:
    laplacian_norm: none
    eigvec_norm: L2
    max_freqs: 10
  model: DeepSet
  dim_pe: 16
  layers: 2
  raw_norm_type: none
train:
  mode: custom
  batch_size: 1
  eval_period: 1
  ckpt_period: 100
model:
  type: GPSModel
  loss_fun: cross_entropy
  edge_decoding: dot
gt:
  layer_type: None+Transformer
  layers: 1
  n_heads: 4
  dim_hidden: 16 # `gt.dim_hidden` must match `gnn.dim_inner`
  dropout: 0.0
  attn_dropout: 0.5
  layer_norm: False
  batch_norm: True
gnn:
  head: inductive_node
  layers_pre_mp: 0
  layers_post_mp: 0 # Not used when `gnn.head: san_graph`
  dim_inner: 16 # `gt.dim_hidden` must match `gnn.dim_inner`
  batchnorm: True
  act: relu
  dropout: 0.0
optim:
  optimizer: adamW
  weight_decay: 0.0
  base_lr: 0.0003
  max_epoch: 5
  scheduler: cosine_with_warmup
  num_warmup_epochs: 10
  min_lr: 1e-5
