out_dir: results
metric_best: accuracy
tensorboard_agg: False
tensorboard_each_run: False
wandb:
  use: False
dataset:
  format: PyG-Amazon
  name: computers
  task: node
  task_type: classification
  transductive: True
  node_encoder: True
  node_encoder_name: LinearNode
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: DummyEdge
  edge_encoder_bn: False
  split: [0.6, 0.2, 0.2]
train:
  mode: custom
  batch_size: 1
  eval_period: 1
  ckpt_period: 100
model:
  type: custom_gnn
  loss_fun: cross_entropy
  edge_decoding: dot
  graph_pooling: add
gvm:
  avg_nodes: 13752
  pool_ratio: 0.0001
  n_pool_heads: 1
gnn:
  # 130 vanilla
  # 88
  layers_pre_mp: 0
  layers_mp: 1
  layers_post_mp: 0
  dim_inner: 16
  layer_type: gatedgcnconv
  act: relu
  residual: True
  dropout: 0.12
optim:
  optimizer: adamW
  weight_decay: 0.0
  base_lr: 0.0003
  max_epoch: 5
  scheduler: cosine_with_warmup
  num_warmup_epochs: 10
  min_lr: 1e-5
